### ISSUE TITLE
SecurityToken is not found by .NET Framework project after upgrade of System.ServiceModel.Primitives from 4.10.3 to 8.1.1 in netstandard2.0 project

### ISSUE THREAD

**Issue by vgriph** [dotnet/wcf#5722]
**Describe the bug**
Version 8.1 of the System.ServiceModel.Primitives brings back netstandard and .NET Framework support to the System.ServiceModel.Primitives package, after it was removed in version 6.0.0. However, after updating the version from 4.10.3 to 8.1.1, when building a .NET Framework project consuming a .NET standard project, exposing the SecurityTopken type in a return parameter, the .NET framework project fails to build with 
> Error CS7069: Reference to type 'SecurityToken' claims it is defined in 'System.ServiceModel.Primitives', but it could not be found

**To Reproduce**
Build the attached solution: [SecurityTokenNotFound.zip](https://github.com/user-attachments/files/18298108/SecurityTokenNotFound.zip)

**Expected behavior**
The solution should build correctly, as it does when downgrading the System.ServiceModel.Primitives package reference to 4.10.3

**Comment by vgriph** [comment]
This seems to be cause by the reference assembly for .NET Framework 4.6.2 (ref\net462\System.ServciceModel.Primitives.dll) not containing the type forwarders.

**Comment by vgriph** [comment]
Found a work-around by adding the following target to the .NET Framework project:
```
	<Target Name="DontUseSystemServiceModelPrimitivesReferenceAssembly" BeforeTargets="ResolveLockFileReferences">
		<ItemGroup>
			<ResolvedCompileFileDefinitions 
				Remove="@(ResolvedCompileFileDefinitions)"
				Condition="'%(PathInPackage)' == 'ref/net462/System.ServiceModel.Primitives.dll' AND '%(NuGetPackageId)' == 'System.ServiceModel.Primitives'" />
			<ResolvedCompileFileDefinitions
				Include="@(RuntimeCopyLocalItems)"
				Condition="'%(PathInPackage)' == 'lib/net462/System.ServiceModel.Primitives.dll' AND '%(NuGetPackageId)' == 'System.ServiceModel.Primitives'" />
		</ItemGroup>
	</Target>
```
